version: '3.3'
services:
  web:
    container_name: Pfadihue-Whatsapp
    image: ghcr.io/lela810/pfadihue-whatsapp:main
    restart: unless-stopped
    network_mode: host
    env_file:
      - stack.env
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - pfadihue-whatsapp:/app/.wwebjs_auth

volumes:
  pfadihue-whatsapp:
